CREATE TABLE AD_MENU_CATEGORIA (
  CODCATEGORIA VARCHAR2(60) NOT NULL,
  NOME         VARCHAR2(120) NOT NULL,
  ICONE        VARCHAR2(80) DEFAULT 'fa-folder' NOT NULL,
  ORDEM        NUMBER(6) DEFAULT 0 NOT NULL,
  ATIVO        CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_AD_MENU_CATEGORIA PRIMARY KEY (CODCATEGORIA),
  CONSTRAINT CK_AD_MENU_CATEGORIA_ATIVO CHECK (ATIVO IN ('S','N'))
);

CREATE TABLE AD_MENU_APLICATIVO (
  CHAVE_APP    VARCHAR2(80) NOT NULL,
  CODCATEGORIA VARCHAR2(60) NOT NULL,
  ORDEM        NUMBER(6) DEFAULT 0 NOT NULL,
  ATIVO        CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_AD_MENU_APLICATIVO PRIMARY KEY (CHAVE_APP),
  CONSTRAINT CK_AD_MENU_APP_ATIVO CHECK (ATIVO IN ('S','N')),
  CONSTRAINT FK_AD_MENU_APP_CAT FOREIGN KEY (CODCATEGORIA)
    REFERENCES AD_MENU_CATEGORIA (CODCATEGORIA)
);

INSERT INTO AD_MENU_CATEGORIA VALUES ('vendas-pdv','Vendas e PDV','fa-cash-register',10,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('estoque-lojas','Estoque e lojas','fa-boxes-stacked',20,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('administracao','Administração','fa-user-shield',30,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('produtos-precos','Produtos e preços','fa-tags',40,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('compras','Compras','fa-truck-loading',50,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('fiscal-notas','Fiscal e notas','fa-file-invoice-dollar',60,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('relatorios','Relatórios','fa-chart-column',70,'S');
INSERT INTO AD_MENU_CATEGORIA VALUES ('financeiro','Financeiro','fa-credit-card',80,'S');

INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('pdv','vendas-pdv',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('faturamento','vendas-pdv',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('consulta-vend','vendas-pdv',30);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('requisicoes','estoque-lojas',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('transferencias','estoque-lojas',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('analise-transf','estoque-lojas',30);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('coletor','estoque-lojas',40);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('gerenciamento-usuarios','administracao',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('gerenciamento-categorias','administracao',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('consulta-custo','produtos-precos',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('calc-custo','produtos-precos',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('pedido-compra','compras',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('orcamento-ocr','compras',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('acomp-notas','fiscal-notas',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('acomp-notas-lite','fiscal-notas',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('receita-despesa','relatorios',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('entrada-saida','relatorios',20);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('financeiro','financeiro',10);
INSERT INTO AD_MENU_APLICATIVO (CHAVE_APP,CODCATEGORIA,ORDEM) VALUES ('baixa-boletos','financeiro',20);
COMMIT;
