CREATE TABLE AD_RECEITA_MANUAL (
  CODEMP NUMBER(5) NOT NULL,
  COMPETENCIA DATE NOT NULL,
  PIX NUMBER(15,2) DEFAULT 0 NOT NULL,
  CARTAO NUMBER(15,2) DEFAULT 0 NOT NULL,
  DEPOSITO NUMBER(15,2) DEFAULT 0 NOT NULL,
  BOLETO NUMBER(15,2) DEFAULT 0 NOT NULL,
  DINHEIRO NUMBER(15,2) DEFAULT 0 NOT NULL,
  VERSAO NUMBER(10) DEFAULT 1 NOT NULL,
  USUARIO VARCHAR2(100 CHAR) NOT NULL,
  ATUALIZADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_AD_RECEITA_MANUAL PRIMARY KEY (CODEMP, COMPETENCIA),
  CONSTRAINT CK_AD_RECEITA_MANUAL_MES CHECK (COMPETENCIA = TRUNC(COMPETENCIA, 'MM')),
  CONSTRAINT CK_AD_RECEITA_MANUAL_VALORES CHECK (
    PIX >= 0 AND CARTAO >= 0 AND DEPOSITO >= 0 AND BOLETO >= 0 AND DINHEIRO >= 0
  )
)
